Revert "ensure 'binman:web' task works the first time thru"
This reverts commit dd0511e78e02546cac4903b5c6de6243607a8bba,
which was causing the following error under Ruby 2.3.0p0.

  % rake build
  mkdir -p man/man1
  rake aborted!
  LoadError: cannot load such file -- md2man/rakefile.rb
  ./lib/binman/rakefile.rb:29:in `load'
  ./lib/binman/rakefile.rb:29:in `block in <top (required)>'
  Tasks: TOP => build => binman => binman:man
  (See full trace by running task with --trace)
  exit 1